USE ALIEXPRESS;

CREATE TABLE MANAGER (
	MANAGER_ID VARCHAR(30) NOT NULL,
	MANAGER_PASSWORD VARCHAR(30) NOT NULL,
	PRIMARY KEY (MANAGER_ID)
) ENGINE = INNODB CHARACTER SET UTF8;

CREATE TABLE CONTACT (
	CONTACT_ID INT(7) NOT NULL AUTO_INCREMENT,
	CONTACT_EMAIL VARCHAR(50) NOT NULL,
	CONTACT_TITLE VARCHAR(100) NOT NULL,
	CONTACT_CONTENT VARCHAR(5000) NOT NULL,
	CONTACT_REG_YMD CHAR(8) NOT NULL,
	CONTACT_REPLY_TITLE VARCHAR(50),
	CONTACT_REPLY_CONTENT VARCHAR(5000),
	CONTACT_READ_YMD VARCHAR(8),
	CONTACT_REPLY_YMD VARCHAR(8),
	PRIMARY KEY (CONTACT_ID)
) ENGINE = INNODB CHARACTER SET UTF8;

CREATE TABLE SERVER (
	SERVER_ID VARCHAR(10) NOT NULL,
	SERVER_APP_URL VARCHAR(50),
	SERVER_APP_KEY VARCHAR(50),
	SERVER_SECRET_KEY VARCHAR(50),
	SERVER_TRACKING_ID VARCHAR(50),
	SERVER_EMAIL_ID VARCHAR(50),
	SERVER_EMAIL_PASSWORD VARCHAR(50),
	SERVER_EMAIL_PLATFORM VARCHAR(5),
	SERVER_YOUTUBE VARCHAR(100),
	SERVER_USER_SITE VARCHAR(100),
	SERVER_USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
	SERVER_DELETABLE_YN CHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY(SERVER_ID)
) ENGINE = INNODB CHARACTER SET UTF8;

CREATE TABLE PROMOTION (
	PROMOTION_ID INT(3) NOT NULL AUTO_INCREMENT,
	PROMOTION_TYPE VARCHAR(10) NOT NULL,
	PROMOTION_TITLE_KO VARCHAR(50) NOT NULL,
	PROMOTION_IMAGE_KO VARCHAR(100) NOT NULL,
	PROMOTION_LINK_KO VARCHAR(100) NOT NULL,
	PROMOTION_TITLE_EN VARCHAR(50) NOT NULL,
	PROMOTION_IMAGE_EN VARCHAR(100) NOT NULL,
	PROMOTION_LINK_EN VARCHAR(100) NOT NULL,
	PROMOTION_START_YMD VARCHAR(8),
	PROMOTION_END_YMD VARCHAR(8),
	PRIMARY KEY(PROMOTION_ID)
) ENGINE = INNODB CHARACTER SET UTF8;
	
CREATE TABLE PRIMARY_CATEGORY (
	PRIMARY_CATEGORY_ID INT(4) NOT NULL AUTO_INCREMENT,
	PRIMARY_CATEGORY_NAME_KO VARCHAR(80) NOT NULL,
	PRIMARY_CATEGORY_NAME_EN VARCHAR(80) NOT NULL,
	PRIMARY KEY (PRIMARY_CATEGORY_ID)
) ENGINE = INNODB CHARACTER SET UTF8;

CREATE TABLE SECONDARY_CATEGORY (
	SECONDARY_CATEGORY_ID INT(5) NOT NULL AUTO_INCREMENT,
	PRIMARY_CATEGORY_ID INT(4) NOT NULL,
	SECONDARY_CATEGORY_NAME_KO VARCHAR(80) NOT NULL,
	SECONDARY_CATEGORY_NAME_EN VARCHAR(80) NOT NULL,
	SECONDARY_CATEGORY_FILE VARCHAR(100),
	PRIMARY KEY (SECONDARY_CATEGORY_ID),
	FOREIGN KEY (PRIMARY_CATEGORY_ID) REFERENCES PRIMARY_CATEGORY (PRIMARY_CATEGORY_ID)
	ON DELETE CASCADE
) ENGINE = INNODB CHARACTER SET UTF8;

CREATE TABLE MAIN_CONTENT (
	MAIN_CONTENT_ID INT(5) NOT NULL AUTO_INCREMENT,
	MAIN_CONTENT_TYPE VARCHAR(6) NOT NULL,
	MAIN_CONTENT_IMAGE_KO VARCHAR(100) NOT NULL,
	MAIN_CONTENT_IMAGE_EN VARCHAR(100) NOT NULL,
	MAIN_CONTENT_DESCRIPTION VARCHAR(100),
	MAIN_CONTENT_ORDER INT(2) NOT NULL,
	PRIMARY KEY (MAIN_CONTENT_ID)
) ENGINE = INNODB CHARACTER SET UTF8;

CREATE TABLE HOT_PRODUCT (
	HOT_PRODUCT_ID INT(8) NOT NULL AUTO_INCREMENT,
	HOT_PRODUCT_PRIMARY_CATEGORY_ID INT(4) NOT NULL,
	HOT_PRODUCT_SECONDARY_CATEGORY_ID INT(5) NOT NULL,
	HOT_PRODUCT_IMAGE VARCHAR(300) NOT NULL,
	HOT_PRODUCT_LINK VARCHAR(300) NOT NULL,
	HOT_PRODUCT_ORIGIN_PRICE VARCHAR(10) NOT NULL,
	HOT_PRODUCT_SALE_PRICE VARCHAR(10),
	PRIMARY KEY (HOT_PRODUCT_ID),
	FOREIGN KEY (HOT_PRODUCT_PRIMARY_CATEGORY_ID) REFERENCES PRIMARY_CATEGORY (PRIMARY_CATEGORY_ID)
	ON DELETE CASCADE,
	FOREIGN KEY (HOT_PRODUCT_SECONDARY_CATEGORY_ID) REFERENCES SECONDARY_CATEGORY (SECONDARY_CATEGORY_ID)
	ON DELETE CASCADE
) ENGINE = INNODB CHARACTER SET UTF8;
DROP TABLE MAIN_CONTENT;

INSERT INTO MANAGER(MANAGER_ID, MANAGER_PASSWORD) VALUES('qowlgh18','1234');

INSERT INTO SERVER(SERVER_ID, SERVER_DELETABLE_YN) VALUES('default', 'N');